CREATE DATABASE ECONNECT;
USE ECONNECT;
#DROP TABLE TRAINING_ENROLLMENTS;
#DROP TABLE TRAINING;
#DROP TABLE USER;

CREATE TABLE USER
(
USER_ID NUMERIC(10,0) NOT NULL UNIQUE,
USER_NAME VARCHAR(255) NOT NULL,
EMAIL VARCHAR(255),
PROFILE_PIC VARCHAR(255),
TRAINER NUMERIC(1,0),
PRIMARY KEY(USER_ID)
);


CREATE TABLE TRAINING
(
TRAINING_ID NUMERIC(10,0) NOT NULL UNIQUE,
TRAINER_ID NUMERIC(10,0) NOT NULL,
DEPARTMENT VARCHAR(25),
RAITING NUMERIC(1,1),
TIME_DURATION VARCHAR(25),

PRIMARY KEY (TRAINING_ID),
FOREIGN KEY (TRAINER_ID) REFERENCES USER(USER_ID)
);


#Lista de training-uri al unui uitlizator se poate realiza prin tabela asta
CREATE TABLE TRAINING_ENROLLMENTS
(
USER_ID NUMERIC(10,0) NOT NULL,
TRAINING_ID NUMERIC(10,0) NOT NULL,

FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID),
FOREIGN KEY (TRAINING_ID) REFERENCES TRAINING(TRAINING_ID)
);

