# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-14 21:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('econnect', '0002_auto_20200512_1505'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='target_user',
            new_name='user',
        ),
    ]
