# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-14 21:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('econnect', '0004_auto_20200515_0036'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='department',
            field=models.CharField(default='No Deptartment', max_length=120),
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default='No Name', max_length=120),
        ),
    ]
