# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-15 00:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('econnect', '0005_auto_20200515_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='default.png', upload_to='uploads'),
        ),
    ]
