# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-23 14:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('econnect', '0006_auto_20200515_0329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='materials',
        ),
        migrations.AddField(
            model_name='profile',
            name='isTrainer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='trainings',
            field=models.ManyToManyField(to='econnect.Training'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='default.png', upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='training',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Trainer',
        ),
    ]
