# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-24 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('econnect', '0007_auto_20200523_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='description',
            field=models.CharField(default='No description has been attached', max_length=5000),
        ),
    ]
