# Generated by Django 3.0.4 on 2020-05-23 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('econnect', '0007_training_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='department',
            field=models.CharField(default='No department', max_length=128),
            preserve_default=False,
        ),
    ]
