# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-24 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('econnect', '0008_training_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='img',
            field=models.ImageField(default='', upload_to='{{training_name}}/photo'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='trainings',
            field=models.ManyToManyField(blank=True, to='econnect.Training'),
        ),
    ]
