# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-24 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('econnect', '0010_training_materials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='materials',
            field=models.FileField(upload_to='{{training_name}}/resources'),
        ),
    ]
