# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-24 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('econnect', '0011_auto_20200524_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='department',
            field=models.CharField(default='No department', max_length=128),
        ),
        migrations.AlterField(
            model_name='training',
            name='img',
            field=models.ImageField(default='static/', upload_to='{{training_name}}/photo'),
        ),
        migrations.AlterField(
            model_name='training',
            name='materials',
            field=models.FileField(upload_to='{{self.training_name }}/resources'),
        ),
    ]
