# Generated by Django 3.0.4 on 2020-05-28 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('econnect', '0016_auto_20200528_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='completed',
            field=models.ManyToManyField(blank=True, related_name='complete', to='econnect.Training'),
        ),
    ]
