# Generated by Django 3.0.4 on 2020-05-28 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('econnect', '0017_profile_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='completed',
        ),
    ]
