# Generated by Django 3.0.6 on 2020-08-14 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('econnect', '0018_remove_profile_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='static/default.png', upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='training',
            name='materials',
            field=models.FileField(blank=True, null=True, upload_to='resources'),
        ),
        migrations.AlterField(
            model_name='training',
            name='next_session',
            field=models.DateTimeField(blank=True, max_length=128, null=True),
        ),
    ]
